- include: "install.yml"

- include: "clean.yml"
  tags:
    - "clean"

- include: "create_ca.yml"

- include: "server.yml"

- include: "user.yml"
  vars:
    username: "{{item}}"
  with_items: "{{users}}"

- include: "configure_nginx.yml"